### ISSUE TITLE
Update game developer roadmap for 2018

### ISSUE THREAD

**Issue by utilForever** [utilForever/game-developer-roadmap#7]
- [x] Update Introduction for 2018
- [ ] Update Client Programmer Roadmap for 2018
- [ ] Update Server Programmer Roadmap for 2018
- [ ] Add Designer Roadmap
- [ ] Add Artist Roadmap
- [ ] Add relevant resources for each

**Comment by GabrielCoelho** [comment]
Hope you're still taking care of this repo! :+1: :pray:

**Comment by utilForever** [comment]
@GabrielCoelho I'm very sorry. I'll try the best. 😢

**Comment by GabrielCoelho** [comment]
*Just don't give up*! Trust in the knowledge of the community and the repo will rise! You have 74 watchers, let them know that the repo it's still alive, let them know that you may need some help to keep upgrading the info. I offer my help, even if I'm really newbie in Game Development. 

**Open Source Communities are wonderful because they bring people together for some major reason!** Keep going! 😄 💪
